import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FADADD',
        paddingTop: 40,
        paddingBottom: 30
    },
    pageTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 15,
        color: '#000000',
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: {width: 1, height: 1},
        textShadowRadius: 2,
    },
    calendarWrapper: {
        width: '90%',
        alignSelf: 'center',
        borderRadius: 16,
        overflow: 'hidden',
        backgroundColor: '#ffffff',
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
        marginTop: 10,
        marginBottom: 15,
        paddingTop: 10,
        paddingBottom: 15,
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 20,
        width: '90%',
    },
    detailsModalContent: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 16,
        width: 'auto',
        alignSelf: 'center',
    },
    closeButtonContainerDetails: {
        position: 'absolute',
        right: 10,
        top: 10,
        zIndex: 10,
    },
    bottomModal: {
        justifyContent: 'flex-end',
        margin: 0,
    },
    centeredEmojiList: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    journalContainer: {
        marginTop: 10,
    },
    journalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    journalDate: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2d4150',
        flex: 1,
    },
    journalEmoji: {
        fontSize: 36
    },
    noteContainer: {
        borderTopWidth: 1,
        borderTopColor: '#ecf0f1',
        paddingTop: 20,
    },
    journalNote: {
        fontSize: 16,
        color: '#7f8c8d',
        lineHeight: 24,
    },
    dayCell: {
        justifyContent: 'space-between',
        alignItems: 'center',
        height: 66,
        width: '100%',
        padding: 2,
        paddingVertical: 4,
    },
    dayText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#000000',
        marginTop: 2,
    },
    plusCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#90a4ae',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 0.15,
        shadowRadius: 1,
        elevation: 2,
    },
    circleContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f1f1f1',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },

    // Style for the touchable emoji container - matching the circle container
    emojiTouchable: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f1f1f1',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    plusSign: {
        fontSize: 20,
        color: '#e0e0e0',
        textAlign: 'center',
        lineHeight: 32,
    },
    placeholderCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#f9f9f9',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    disabledText: {
        color: '#90a4ae',
    },
    otherMonthText: {
        color: '#cfd8dc',
    },
    moodCircle: {
        backgroundColor: '#f1f1f1',
        borderRadius: 20,
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {width: 2, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 8,
        borderWidth: 2,
        borderTopColor: '#fff',
        borderLeftColor: '#fff',
        borderRightColor: '#ccc',
        borderBottomColor: '#ccc',
    },
    emojiContainer: {
        position: 'relative',
    },
    emoji: {
        fontSize: 20,
        lineHeight: 36,
    },
    emojiBase: {
        position: 'relative',
        top: -1,
        left: -1,
    },
    emojiShadow: {
        position: 'absolute',
        color: 'rgba(0,0,0,0.15)',
        top: 1,
        left: 1,
    },
    otherMonthEmoji: {
        color: '#cfd8dc',
    },
    placeholderContainer: {
        width: 38,
        height: 38,
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderEmoji: {
        fontSize: 20,
        color: '#90a4ae',
    },
    plusContainer: {
        width: 38,
        height: 38,
        justifyContent: 'center',
        alignItems: 'center',
    },
    plusSignShadow: {
        position: 'absolute',
        color: 'rgba(0,0,0,0.15)',
        top: 1,
        left: 1,
    },
    otherMonthPlus: {
        color: '#cfd8dc',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        marginBottom: 15,
        position: 'relative',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '600',
        textAlign: 'center',
        color: '#000000',
    },
    closeButtonContainer: {
        position: 'absolute',
        right: 0,
    },
    closeButton: {
        fontSize: 28,
        color: '#000000',
        paddingHorizontal: 10,
    },
    dateText: {
        marginBottom: 15,
        fontSize: 16,
        color: '#1976d2',
        textDecorationLine: 'underline',
    },
    textInput: {
        width: '100%',
        borderColor: '#90caf9',
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        fontSize: 16,
        backgroundColor: '#f9f9f9',
        marginBottom: 20,
        textAlignVertical: 'top',
        minHeight: 80,
    },
    scrollIndicator: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5,
        height: 10,
    },
    scrollDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#e0e0e0',
        marginHorizontal: 2,
    },
    scrollDotActive: {
        backgroundColor: '#1976d2',
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        marginBottom: 15,
        position: 'relative',
    },
    cancelButton: {
        backgroundColor: '#e3f2fd',
        padding: 12,
        borderRadius: 10,
        width: '45%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#90caf9',
    },
    saveButton: {
        backgroundColor: '#BA5F5F',
        padding: 12,
        borderRadius: 10,
        width: '45%',
        alignItems: 'center',
    },
    cancelButtonText: {
        color: '#0d47a1',
        fontWeight: 'bold',
    },
    saveButtonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    datePickerModal: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 20,
        maxHeight: '80%',
    },
    dateItem: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    selectedDateItem: {
        backgroundColor: '#e3f2fd',
    },
    dateItemText: {
        fontSize: 16,
        color: '#000000',
    },
    dateItemMood: {
        fontSize: 24,
    },
    entryListContainer: {
        flex: 1,
        backgroundColor: '#FADADD',
    },
    entryListHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#BA5F5F',
        borderBottomWidth: 1,
        borderBottomColor: '#90caf9',
    },
    backButton: {
        padding: 8,
    },
    backButtonText: {
        color: '#000000',
        fontSize: 16,
        fontWeight: '500',
    },
    entryListTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000000',
    },
    placeholder: {
        width: 80,
    },
    entryListContent: {
        padding: 12,
    },
    entrySeparator: {
        height: 12,
    },
    entryItem: {
        backgroundColor: '#fff',
        borderRadius: 8,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
        elevation: 2,
    },
    entriesButton: {
        backgroundColor: '#1976d2',
        padding: 12,
        borderRadius: 8,
        margin: 16,
        alignItems: 'center',
    },
    entriesButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    // Table styles for entries
    journalTable: {
        width: '100%',
    },
    journalRow: {
        flexDirection: 'row',
        alignItems: 'stretch',
    },
    journalEmoticonCell: {
        padding: 16,
        borderRightWidth: 1,
        borderRightColor: '#e0e0e0',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f8f8f8',
        width: 80,
    },
    journalEmoticonText: {
        fontSize: 42,
    },
    journalInfoCell: {
        flex: 1,
        padding: 16,
        justifyContent: 'center',
    },
    journalDateText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#000000',
        marginBottom: 8,
    },
    journalNoteText: {
        fontSize: 14,
        color: '#000000',
        lineHeight: 20,
    },
    compactModalContent: {
        backgroundColor: 'white',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        paddingTop: 10,
    },
    dateContainer: {
        alignItems: 'center',
        marginVertical: 10,
    },
    emojiList: {
        paddingHorizontal: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emojiOption: {
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4,
    },
    emojiOptionSmall: {
        padding: 2,
    },
    centeredContent: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        marginVertical: 10,
    },
    dragIndicator: {
        alignSelf: 'center',
        width: 40,
        height: 5,
        borderRadius: 5,
        backgroundColor: '#ccc',
        marginBottom: 10,
    },
    compactTextInput: {
        borderColor: '#BA5F5F',
        borderWidth: 1,
        borderRadius: 10,
        padding: 12,
        fontSize: 16,
        backgroundColor: '#f9f9f9',
        marginVertical: 16,
        textAlignVertical: 'top',
        minHeight: 100,
        maxHeight: 150,
    },
    selectedMoodContainer: {
        alignItems: 'center',
        marginBottom: 15,
        marginTop: 10,
    },
    moodCircleEnhanced: {
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 3},
        shadowOpacity: 0.27,
        shadowRadius: 4.65,
        elevation: 6,
        backgroundColor: '#fff',
        borderRadius: 25,
        padding: 5,
    },
});

export default styles;
